const SAVE_KEY='last_shelter_v5_6_3_save';
const timeSlots=['Matin','Après-midi','Soir','Nuit'];
const weatherDefs=[{id:'clear',label:'☀️ Temps clair'},{id:'rain',label:'🌧️ Pluie froide'},{id:'fog',label:'🌫️ Brouillard'},{id:'cold',label:'❄️ Froid sec'}];
const icons={food:'🍖',water:'💧',bandage:'🩹',medicine:'💊',ammo:'🔸',materials:'🧱',fuel:'⛽'};
const locationDefs=[
{id:'house',name:'Maison abandonnée',risk:34,loot:'nourriture',desc:'Cuisine fouillée, placards encore partiellement remplis.',rewards:{food:[1,3],water:[0,1],materials:[0,2],bandage:[0,1]}},
{id:'pharmacy',name:'Pharmacie',risk:46,loot:'soins',desc:'Réserve médicale fracturée, mais encore exploitable.',rewards:{bandage:[1,2],medicine:[0,1],water:[0,1],materials:[0,1]}},
{id:'market',name:'Supérette',risk:56,loot:'provisions',desc:'Rayons vides, réserve du fond peut encore cacher des rations.',rewards:{food:[1,3],water:[1,3],materials:[0,1]}},
{id:'garage',name:'Garage',risk:42,loot:'matériaux',desc:'Ferraille, outils et parfois un peu de carburant.',rewards:{materials:[2,4],fuel:[0,1],water:[0,1]}},
{id:'hospital',name:'Hôpital',risk:66,loot:'médical',desc:'Grand bâtiment instable, très riche mais très exposé.',rewards:{bandage:[1,3],medicine:[0,2],food:[0,1],water:[0,1]}},
{id:'police',name:'Commissariat',risk:72,loot:'munitions',desc:'Zone dangereuse, rentable si tu en reviens vivant.',rewards:{ammo:[1,3],materials:[1,2],bandage:[0,1]}}
];
const buildingDefs=[
{id:'rainCollector',name:'Récupérateur d’eau',desc:'Produit de l’eau pendant la pluie.',cost:{materials:4}},
{id:'garden',name:'Petit potager',desc:'Produit de la nourriture tous les quelques jours.',cost:{materials:5,water:1}},
{id:'medicalCorner',name:'Coin médical',desc:'Rend les soins plus efficaces.',cost:{materials:4,medicine:1}},
{id:'bed',name:'Lit amélioré',desc:'Dormir récupère davantage d’énergie.',cost:{materials:3,food:1}}
];
const explorationEvents=[
{title:'Coupure sale',text:'En fouillant un tiroir brisé, tu te coupes profondément sur du métal rouillé.',choices:[
{label:'Nettoyer vite et continuer',desc:'Risque d’infection',effect(s){s.stats.health=clamp(s.stats.health-4);s.stats.infection=clamp(s.stats.infection+10);addLog('Coupure sale','Tu continues malgré la blessure. L’infection grimpe.','Danger');toast('Infection','Infection +10. Santé -4.','danger');}},
{label:'Rentrer immédiatement',desc:'Moins de risque',effect(s){s.stats.health=clamp(s.stats.health-2);s.stats.infection=clamp(s.stats.infection+4);addLog('Retour précipité','Tu écourtes la sortie après une coupure inquiétante.','Danger');toast('Blessure','Infection +4. Santé -2.','warning');}}
]},
{title:'Air contaminé',text:'L’odeur dans le bâtiment est irrespirable. Tu tousses et tes yeux brûlent.',choices:[
{label:'Forcer encore un peu',desc:'Butin possible mais infection',effect(s){s.stats.infection=clamp(s.stats.infection+8);s.inventory.food+=1;s.statsSummary.resourcesFound+=1;addLog('Air contaminé','Tu insistes malgré l’air toxique et trouves une ration.','Danger');toast('Air contaminé','Infection +8, +1 ration.','warning');}},
{label:'Sortir prendre l’air',desc:'Rester prudent',effect(s){s.stats.stress=clamp(s.stats.stress-1);addLog('Repli prudent','Tu préfères sortir pour éviter d’aggraver ton état.','Danger');toast('Prudence','Tu évites le pire.','info');}}
]}
];

function initialState(){return{day:1,timeIndex:0,location:'Abri',weather:'clear',shelter:58,noise:18,danger:22,lastSavedAt:null,nightGuard:0,deathReason:null,statsSummary:{explorations:0,attacks:0,resourcesFound:0},buildings:{rainCollector:{built:false},garden:{built:false,lastHarvestDay:1},medicalCorner:{built:false},bed:{built:false}},inventory:{food:4,water:4,bandage:2,medicine:0,ammo:3,materials:5,fuel:0},stats:{health:84,hunger:68,thirst:70,energy:76,morale:61,infection:8,stress:34},log:[]}}
let state=initialState();
const statsConfig=[{key:'health',label:'Santé',tone:'success'},{key:'hunger',label:'Faim',tone:'warning'},{key:'thirst',label:'Soif',tone:'warning'},{key:'energy',label:'Énergie',tone:'success'},{key:'morale',label:'Moral',tone:'success'},{key:'infection',label:'Infection',tone:'danger'},{key:'stress',label:'Stress',tone:'danger'}];
const $=id=>document.getElementById(id);
const startScreen=$('startScreen'),gameApp=$('gameApp'),continueBtn=$('continueBtn'),newGameBtn=$('newGameBtn'),resetSaveBtn=$('resetSaveBtn'),saveNowBtn=$('saveNowBtn'),stickyActions=$('stickyActions'),buildingsToggle=$('buildingsToggle'),explorationToggle=$('explorationToggle'),journalToggle=$('journalToggle'),buildingsContent=$('buildingsContent'),explorationContent=$('explorationContent'),journalContent=$('journalContent'),moreActionsBtn=$('moreActionsBtn'),moreActionsPanel=$('moreActionsPanel');
const stickyVitals=$('stickyVitals'),stickyResources=$('stickyResources'),statusSummary=$('statusSummary'),statsGrid=$('statsGrid'),statusChips=$('statusChips'),overviewGrid=$('overviewGrid'),inventoryList=$('inventoryList'),journalDays=$('journalDays'),dayLabel=$('dayLabel'),timeLabel=$('timeLabel'),locationLabel=$('locationLabel'),locationsGrid=$('locationsGrid'),buildingsGrid=$('buildingsGrid'),saveStateLabel=$('saveStateLabel'),weatherLabel=$('weatherLabel'),ambienceText=$('ambienceText'),gameOverScreen=$('gameOverScreen'),gameOverReason=$('gameOverReason'),gameOverStats=$('gameOverStats'),restartBtn=$('restartBtn'),backMenuBtn=$('backMenuBtn'),eventModal=$('eventModal'),eventTitle=$('eventTitle'),eventText=$('eventText'),eventChoices=$('eventChoices');

document.querySelectorAll('[data-action]').forEach(btn=>btn.addEventListener('click',()=>handleAction(btn.dataset.action)));
continueBtn.addEventListener('click',continueGame); newGameBtn.addEventListener('click',startNewGame); resetSaveBtn.addEventListener('click',resetSave);
saveNowBtn.addEventListener('click',()=>{save();toast('Sauvegarde','Partie sauvegardée.','success')});
restartBtn.addEventListener('click',()=>{gameOverScreen.classList.add('hidden');startNewGame()});
backMenuBtn.addEventListener('click',()=>{gameOverScreen.classList.add('hidden');toggleGame(false)});
moreActionsBtn.addEventListener('click',()=>moreActionsPanel.classList.toggle('hidden'));
buildingsToggle.addEventListener('click',()=>toggleAccordion(buildingsToggle,buildingsContent));
explorationToggle.addEventListener('click',()=>toggleAccordion(explorationToggle,explorationContent));
journalToggle.addEventListener('click',()=>toggleAccordion(journalToggle,journalContent));

function toggleAccordion(trigger, content){const open=trigger.getAttribute('aria-expanded')==='true';trigger.setAttribute('aria-expanded', String(!open));content.classList.toggle('hidden', open)}
function clamp(v,min=0,max=100){return Math.max(min,Math.min(max,v))}
function randomInt(min,max){return Math.floor(Math.random()*(max-min+1))+min}
function pick(arr){return arr[randomInt(0,arr.length-1)]}
function save(){state.lastSavedAt=new Date().toISOString();localStorage.setItem(SAVE_KEY,JSON.stringify(state));renderSaveLabel();continueBtn.disabled=false}
function load(){const raw=localStorage.getItem(SAVE_KEY);if(!raw)return null;try{return JSON.parse(raw)}catch{return null}}
function toggleGame(show){startScreen.classList.toggle('hidden',show);gameApp.classList.toggle('hidden',!show);stickyActions.classList.toggle('hidden',!show)}
function addLog(title,text,tag='Système'){state.log.unshift({title,text,tag,time:`Jour ${state.day} • ${timeSlots[state.timeIndex]}`});state.log=state.log.slice(0,20)}
function toast(title,message,type='info',duration=2600){const c=$('toastContainer');const t=document.createElement('div');t.className=`toast ${type}`;t.innerHTML=`<div class="toast-top"><div class="toast-title">${title}</div><button class="toast-close">×</button></div><div class="toast-message">${message}</div>`;const rm=()=>{if(!t.isConnected)return;t.classList.add('hide');setTimeout(()=>t.isConnected&&t.remove(),240)};t.querySelector('.toast-close').addEventListener('click',rm);c.prepend(t);setTimeout(rm,duration)}
function getWeatherLabel(id){return weatherDefs.find(x=>x.id===id)?.label||'☀️ Temps clair'}
function rollWeather(){state.weather=pick(weatherDefs).id}
function startNewGame(){state=initialState();addLog('Début de survie','Tu verrouilles l’abri. Tout est précaire, mais chaque amélioration peut faire la différence.','Prologue');toggleGame(true);save();render();toast('Nouvelle partie','La V5.6.3 démarre.','success')}
function continueGame(){const saved=load();if(!saved){toast('Aucune sauvegarde','Commence une nouvelle partie.','warning');return}state=saved;toggleGame(true);render();toast('Continuer','Sauvegarde chargée.','info')}
function resetSave(){localStorage.removeItem(SAVE_KEY);continueBtn.disabled=true;toast('Sauvegarde effacée','La progression enregistrée a été supprimée.','warning')}
function payCost(cost){for(const [k,v] of Object.entries(cost)){if((state.inventory[k]||0)<v)return false}for(const [k,v] of Object.entries(cost)){state.inventory[k]-=v}return true}
function buildStructure(id){const def=buildingDefs.find(b=>b.id===id);if(!def)return;if(state.buildings[id].built){toast('Déjà construit','Cette amélioration est déjà en place.','info');return}if(!payCost(def.cost)){toast('Ressources insuffisantes','Tu n’as pas ce qu’il faut pour construire ça.','warning');return}state.buildings[id].built=true;if(id==='garden')state.buildings[id].lastHarvestDay=state.day;addLog('Construction',`${def.name} installé dans l’abri.`,'Abri');toast('Construction terminée',def.name,'success');save();render()}
function applyPassiveProduction(){if(state.buildings.rainCollector.built&&state.weather==='rain'){const gain=randomInt(1,3);state.inventory.water+=gain;state.statsSummary.resourcesFound+=gain;addLog('Récupération d’eau',`Le récupérateur d’eau te fournit ${gain} bouteille(s).`,'Abri');toast('Pluie utile',`+${gain} eau grâce au récupérateur.`,'success')}if(state.buildings.garden.built&&state.day-state.buildings.garden.lastHarvestDay>=3){const gain=randomInt(2,4);state.inventory.food+=gain;state.statsSummary.resourcesFound+=gain;state.buildings.garden.lastHarvestDay=state.day;addLog('Récolte',`Le potager fournit ${gain} ration(s).`,'Abri');toast('Potager',`+${gain} nourriture récoltée.`,'success')}}
function advanceTime(){state.timeIndex+=1;state.stats.hunger=clamp(state.stats.hunger-randomInt(5,9));state.stats.thirst=clamp(state.stats.thirst-randomInt(6,10));state.stats.energy=clamp(state.stats.energy-randomInt(5,8));state.stats.morale=clamp(state.stats.morale-randomInt(1,3));state.stats.stress=clamp(state.stats.stress+randomInt(1,4));state.noise=clamp(state.noise-randomInt(1,3));state.danger=clamp(state.danger+randomInt(1,4));if(state.stats.hunger<25)state.stats.health=clamp(state.stats.health-4);if(state.stats.thirst<25)state.stats.health=clamp(state.stats.health-6);if(state.stats.energy<20)state.stats.health=clamp(state.stats.health-3);if(state.stats.infection>40)state.stats.health=clamp(state.stats.health-5);if(state.timeIndex>3){state.timeIndex=0;state.day+=1;state.location='Abri';rollWeather();applyPassiveProduction();nightEvent()}checkDeath()}
function nightEvent(){let attackRisk=state.danger+state.noise-Math.floor(state.shelter/2)-state.nightGuard;state.nightGuard=0;if(attackRisk>60){const dmg=randomInt(6,14);const shelterDmg=randomInt(8,16);state.stats.health=clamp(state.stats.health-dmg);state.shelter=Math.max(0,state.shelter-shelterDmg);state.statsSummary.attacks+=1;addLog('Attaque nocturne',`Des rôdeurs frappent l’abri pendant la nuit. Santé -${dmg}, protection -${shelterDmg}.`,'Nuit');toast('Attaque nocturne',`Santé -${dmg}. Abri -${shelterDmg}.`,'danger')}else{state.stats.energy=clamp(state.stats.energy+8);addLog('Nuit calme','La nuit reste tendue mais silencieuse. L’abri tient bon.','Nuit');toast('Nuit calme','L’abri a tenu cette nuit.','success')}checkDeath()}
function checkDeath(){if(state.shelter<=0){showGameOver("l'abri a cédé");return}if(state.stats.health>0)return;const reason=state.stats.infection>=75?'infection avancée':state.stats.thirst<=0?'déshydratation':state.stats.hunger<=0?'famine':'blessures trop graves';showGameOver(reason)}
function handleAction(action){if(!moreActionsPanel.classList.contains('hidden'))moreActionsPanel.classList.add('hidden');switch(action){case 'sleep':state.location='Abri';state.stats.energy=clamp(state.stats.energy+(state.buildings.bed.built?randomInt(24,34):randomInt(18,28)));addLog('Repos','Tu t’allonges enfin. Même le silence semble fragile.','Abri');toast('Repos','L’énergie remonte.','info');advanceTime();break;case 'eat':if(state.inventory.food<=0){toast('Famine','Aucune ration disponible.','warning');return}state.inventory.food-=1;state.stats.hunger=clamp(state.stats.hunger+24);toast('Repas','1 ration consommée.','success');break;case 'drink':if(state.inventory.water<=0){toast('Déshydratation','Aucune eau disponible.','warning');return}state.inventory.water-=1;state.stats.thirst=clamp(state.stats.thirst+24);toast('Hydratation','1 eau consommée.','success');break;case 'heal':if(state.inventory.bandage<=0){toast('Soin impossible','Aucun bandage disponible.','warning');return}state.inventory.bandage-=1;state.stats.health=clamp(state.stats.health+(state.buildings.medicalCorner.built?20:14));state.stats.infection=clamp(state.stats.infection-8);toast('Soins','Tu te remets partiellement sur pied.','success');break;case 'fortify':if((state.inventory.materials||0)<2){toast('Abri','Pas assez de matériaux.','warning');return}state.inventory.materials-=2;state.shelter=clamp(state.shelter+14);toast('Protection','L’abri est renforcé.','success');advanceTime();break;case 'night-watch':state.nightGuard=clamp(state.nightGuard+18,0,40);state.stats.energy=clamp(state.stats.energy-8);toast('Veille préparée','Le risque nocturne baisse.','success');advanceTime();break;case 'relax':state.stats.stress=clamp(state.stats.stress-randomInt(8,14));state.stats.morale=clamp(state.stats.morale+randomInt(3,6));state.stats.energy=clamp(state.stats.energy+2);addLog('Moment de calme','Tu prends quelques minutes pour souffler et laisser la tension redescendre.','Mental');toast('Se détendre','Le stress baisse.','success');advanceTime();break;case 'next':addLog('Temps qui passe','Tu laisses filer quelques heures dans l’abri.','Temps');toast('Temps','Quelques heures passent.','info');advanceTime();break}save();render()}
function exploreLocation(id){const loc=locationDefs.find(l=>l.id===id);if(!loc)return;state.location=loc.name;state.statsSummary.explorations+=1;const rewards={};Object.entries(loc.rewards).forEach(([k,[min,max]])=>rewards[k]=randomInt(min,max));Object.entries(rewards).forEach(([k,v])=>{state.inventory[k]=(state.inventory[k]||0)+v;state.statsSummary.resourcesFound+=v});state.stats.energy=clamp(state.stats.energy-randomInt(10,16));state.stats.thirst=clamp(state.stats.thirst-randomInt(8,12));state.stats.hunger=clamp(state.stats.hunger-randomInt(5,8));state.noise=clamp(state.noise+randomInt(6,14));state.danger=clamp(state.danger+randomInt(4,10));addLog('Exploration',`Tu fouilles ${loc.name} et récupères ${formatRewardText(rewards)}.`,'Expédition');toast(loc.name,`Butin : ${formatRewardText(rewards)}.`,'success');if(Math.random()<0.58)openEvent(pick(explorationEvents));advanceTime();save();render()}
function openEvent(ev){eventTitle.textContent=ev.title;eventText.textContent=ev.text;eventChoices.innerHTML='';ev.choices.forEach(choice=>{const b=document.createElement('button');b.className='btn';b.innerHTML=`<strong>${choice.label}</strong><span>${choice.desc}</span>`;b.addEventListener('click',()=>{choice.effect(state);eventModal.classList.add('hidden');save();render()});eventChoices.appendChild(b)});eventModal.classList.remove('hidden')}
function formatRewardText(rewards){const labels={food:'ration',water:'eau',bandage:'bandage',medicine:'médicament',ammo:'munition',materials:'matériau',fuel:'carburant'};return Object.entries(rewards).filter(([,v])=>v>0).map(([k,v])=>`${v} ${labels[k]||k}${v>1&&k==='materials'?'x':''}`).join(', ').replace(/([0-9]+) matériau x/g,'$1 matériaux').replace(/1 matériau x/g,'1 matériau')||'rien d’utile'}
function renderSaveLabel(){if(!state.lastSavedAt){saveStateLabel.textContent='Aucune sauvegarde';return}const d=new Date(state.lastSavedAt);saveStateLabel.textContent=`Sauvegardé à ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function showGameOver(reason){state.deathReason=reason;gameOverReason.textContent=`Tu as survécu ${state.day} jour(s). Cause de la mort : ${reason}.`;gameOverStats.innerHTML=[{label:'Jours survécus',value:state.day},{label:'Explorations',value:state.statsSummary.explorations},{label:'Ressources trouvées',value:state.statsSummary.resourcesFound},{label:'Attaques nocturnes',value:state.statsSummary.attacks},{label:'Abri final',value:`${state.shelter}%`},{label:'Météo finale',value:getWeatherLabel(state.weather)}].map(item=>`<article class="game-over-stat"><span>${item.label}</span><strong>${item.value}</strong></article>`).join('');gameOverScreen.classList.remove('hidden')}
function getStatusSummary(){if(state.shelter<=15)return'Abris critique';if(state.stats.health<=25)return'État critique';if(state.stats.infection>=50)return'Infection préoccupante';if(state.stats.thirst<=25)return'Déshydratation imminente';if(state.stats.hunger<=25)return'Famine en approche';if(state.stats.stress>=70)return'Stress très élevé';return'Situation stable'}
function getChips(){const c=[];if(state.stats.health<=35)c.push({text:'Blessé',type:'alert'});if(state.stats.infection>=35)c.push({text:'Infection',type:'alert'});if(state.stats.stress>=65)c.push({text:'Stress élevé',type:'alert'});if(state.stats.energy<=30)c.push({text:'Épuisé',type:'alert'});if(state.shelter>=70)c.push({text:'Abri solide',type:'good'});if(state.inventory.water>=4)c.push({text:'Eau suffisante',type:'good'});if(state.buildings.rainCollector.built)c.push({text:'Collecteur actif',type:'good'});if(state.buildings.garden.built)c.push({text:'Potager',type:'good'});if(!c.length)c.push({text:'Aucun statut majeur',type:''});return c}
function getAmbienceText(){const time=timeSlots[state.timeIndex];const weather=getWeatherLabel(state.weather).replace(/^.. /,'').toLowerCase();if(state.stats.stress>=70)return`Chaque bruit te semble anormal. ${time} sous ${weather}, et ton esprit commence à fatiguer.`;if(state.stats.hunger<=25)return`Ton ventre te serre. ${time} dans l’abri, mais sortir sans manger serait risqué.`;if(time==='Nuit')return`La nuit étouffe les sons puis les amplifie soudainement. Le moindre choc dehors semble tout proche.`;if(state.weather==='rain')return`La pluie tambourine sur le toit. Pour une fois, le mauvais temps peut t’aider à récupérer de l’eau.`;if(state.weather==='fog')return`Le brouillard avale les silhouettes. Dehors, tout paraît plus lent et plus inquiétant.`;if(state.weather==='cold')return`Le froid sec vide doucement tes forces. Même dans l’abri, l’air reste mordant.`;return`Le quartier paraît presque vide, mais ce calme n’est jamais rassurant. ${time} sous ${weather}.`}
function renderSticky(){stickyVitals.innerHTML=[['❤️','Santé',state.stats.health],['🍖','Faim',state.stats.hunger],['💧','Soif',state.stats.thirst],['⚡','Énergie',state.stats.energy]].map(([i,l,v])=>`<div class="sticky-pill"><span class="icon">${i}</span><div><strong>${v}%</strong><span>${l}</span></div></div>`).join('');stickyResources.innerHTML=[['food','Nourriture',state.inventory.food],['water','Eau',state.inventory.water],['materials','Matériaux',state.inventory.materials],['bandage','Bandages',state.inventory.bandage]].map(([k,l,v])=>`<div class="sticky-pill"><span class="icon">${icons[k]}</span><div><strong>${v}</strong><span>${l}</span></div></div>`).join('');statusSummary.textContent=getStatusSummary()}
function renderStats(){statsGrid.innerHTML='';statsConfig.forEach(item=>{const value=clamp(state.stats[item.key]);const card=document.createElement('article');card.className='stat';const fill=document.createElement('div');fill.className=`bar-fill ${item.tone}`;fill.style.width=`${value}%`;card.innerHTML=`<div class="stat-top"><span>${item.label}</span><span>${value}%</span></div><div class="bar"></div>`;card.querySelector('.bar').appendChild(fill);statsGrid.appendChild(card)})}
function renderChips(){statusChips.innerHTML='';getChips().forEach(ch=>{const el=document.createElement('div');el.className=`chip ${ch.type||''}`.trim();el.textContent=ch.text;statusChips.appendChild(el)})}
function renderOverview(){overviewGrid.innerHTML=[{label:'Protection abri',value:`${state.shelter}%`},{label:'Niveau de bruit',value:`${state.noise}%`},{label:'Danger extérieur',value:`${state.danger}%`},{label:'Lieu actuel',value:state.location}].map(i=>`<article class="info"><span>${i.label}</span><strong>${i.value}</strong></article>`).join('')}
function renderBuildings(){buildingsGrid.innerHTML=buildingDefs.map(def=>{const built=state.buildings[def.id].built;const costText=Object.entries(def.cost).map(([k,v])=>`${icons[k]||''} ${v} ${k==='materials'?'matériaux':k==='food'?'nourriture':k==='water'?'eau':k==='medicine'?'médicaments':k}`).join(', ');return `<article class="building-card"><div class="building-top"><strong>${def.name}</strong><span class="badge ${built?'good':'loot'}">${built?'Construit':'À construire'}</span></div><p class="modal-text">${def.desc}</p><div class="location-meta"><span class="badge">${costText}</span></div><button class="btn ${built?'':'primary'} build-btn" data-building="${def.id}" ${built?'disabled':''}><strong>${built?'Déjà installé':'Construire'}</strong><span>${built?'Amélioration active dans l’abri':'Lancer la construction'}</span></button></article>`}).join('');document.querySelectorAll('.build-btn').forEach(btn=>btn.addEventListener('click',()=>buildStructure(btn.dataset.building)))}
function renderLocations(){locationsGrid.innerHTML=locationDefs.map(loc=>`<article class="location-card"><div class="location-top"><div><strong>${loc.name}</strong><p class="modal-text">${loc.desc}</p></div></div><div class="location-meta"><span class="badge danger">Danger ${loc.risk}%</span><span class="badge loot">Butin ${loc.loot}</span></div><button class="btn primary explore-btn" data-location="${loc.id}"><strong>Explorer</strong><span>Sortie vers ${loc.name}</span></button></article>`).join('');document.querySelectorAll('.explore-btn').forEach(btn=>btn.addEventListener('click',()=>exploreLocation(btn.dataset.location)))}
function renderInventory(){const labels={food:['Nourriture','Rations et conserves'],water:['Eau','Bouteilles récupérées'],bandage:['Bandages','Soins d’urgence'],medicine:['Médicaments','Antiseptiques et antibiotiques'],ammo:['Munitions','Derniers chargeurs'],materials:['Matériaux','Planches, métal, outils'],fuel:['Carburant','Réserves rares']};inventoryList.innerHTML=Object.entries(state.inventory).map(([k,v])=>{const [l,d]=labels[k]||[k,'Ressource'];return`<article class="loot-row"><div style="display:flex;align-items:center;gap:10px"><span class="icon">${icons[k]||'📦'}</span><div><strong>${l}</strong><small>${d}</small></div></div><strong>x${v}</strong></article>`}).join('')}
function renderJournal(){const groups={};state.log.forEach(entry=>{const m=entry.time.match(/Jour\s+(\d+)/);const day=m?m[1]:'?';(groups[day]||(groups[day]=[])).push(entry)});const days=Object.keys(groups).sort((a,b)=>Number(b)-Number(a));journalDays.innerHTML=days.map(day=>`<section class="journal-day"><h3>Jour ${day}</h3><div class="journal-entries">${groups[day].map(e=>`<article class="entry"><div class="entry-meta"><span>${e.tag}</span><span>${e.time.replace(/^Jour\s+\d+\s+•\s+/,'')}</span></div><strong>${e.title}</strong><p>${e.text}</p></article>`).join('')}</div></section>`).join('')}
function renderHeader(){dayLabel.textContent=state.day;timeLabel.textContent=timeSlots[state.timeIndex];locationLabel.textContent=state.location;renderSaveLabel();weatherLabel.textContent=getWeatherLabel(state.weather);ambienceText.textContent=getAmbienceText()}
function render(){renderHeader();renderSticky();renderStats();renderChips();renderOverview();renderBuildings();renderLocations();renderInventory();renderJournal()}
(function init(){const saved=load();continueBtn.disabled=!saved;if(saved)state=saved})();